#version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    container_name: wordpress-cms  
    volumes:
      - ./wordpress-data:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin123
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
